export const DFDL_ASSERT_ELEMENT_NAME = 'dfdl:assert'
export const DFDL_DEFINE_VARIABLE_ELEMENT_NAME = 'dfdl:defineVariable'
export const DFDL_DISCRIMINATOR_ELEMENT_NAME = 'dfdl:discriminator'

export default {
  DFDL_DISCRIMINATOR_ELEMENT_NAME: DFDL_DISCRIMINATOR_ELEMENT_NAME,
  DFDL_DEFINE_VARIABLE: DFDL_DEFINE_VARIABLE_ELEMENT_NAME,
  DFDL_ASSERT_ELEMENT_NAME: DFDL_ASSERT_ELEMENT_NAME,
}
